export function siteCss() {
  return `
:root{--bg:#0b0b0c;--paper:#111112;--paper-2:#151313;--ink:#f4f1ef;--text:#aaa2a0;--muted:#7b7472;--line:#201f20;--line-strong:#292728;--soft:#1b1513;--brand:#ff8a5f;--brand-2:#d15035;--code:#1b1a1a;--code-text:#e7ded9;--shadow:0 20px 70px rgba(0,0,0,.34);color-scheme:dark}
:root[data-theme="light"]{--bg:#fbfaf7;--paper:#fffdfa;--paper-2:#fffaf4;--ink:#171514;--text:#413b37;--muted:#716a66;--line:#e8ddd5;--line-strong:#ded0c7;--soft:#f6e9e1;--brand:#d75a37;--brand-2:#b64227;--code:#15120f;--code-text:#f5efe8;--shadow:0 20px 70px rgba(32,24,18,.10);color-scheme:light}
*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:132px}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.75 ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;-webkit-font-smoothing:antialiased}a{color:inherit;text-decoration:none}a:hover{color:var(--ink)}img{max-width:100%;height:auto}button,input,select{font:inherit}.hidden{display:none!important}:root[data-theme="dark"] .dark\\:hidden{display:none!important}:root[data-theme="dark"] .dark\\:block{display:block!important}:root[data-theme="light"] .dark\\:block{display:none!important}
.site-header{position:sticky;top:0;z-index:30;background:color-mix(in srgb,var(--bg) 92%,transparent);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}.header-row,.tabs,.doc-shell{max-width:1280px;margin:0 auto}.header-row{height:70px;display:grid;grid-template-columns:260px minmax(260px,430px) 1fr;gap:28px;align-items:center;padding:0 22px}.header-left{display:flex;align-items:center;gap:15px;min-width:0}.brand{display:inline-flex;align-items:center;flex:0 0 auto}.brand img{width:25px;height:25px;image-rendering:pixelated}.header-left select{min-width:132px;border:0;background:transparent;color:var(--ink);outline:0;padding:7px 0;font-size:14px}.search-button{height:38px;border:1px solid var(--line-strong);border-radius:10px;background:var(--paper);color:var(--muted);display:flex;align-items:center;justify-content:space-between;gap:16px;padding:0 15px;cursor:pointer;text-align:left}.search-button:hover{border-color:color-mix(in srgb,var(--brand) 42%,var(--line));color:var(--text)}.search-button span{font-size:12px;color:var(--muted)}.header-links{display:flex;align-items:center;justify-content:flex-end;gap:18px;color:var(--muted);font-size:14px;white-space:nowrap}.header-links a:hover{color:var(--ink)}.header-links button{border:0;background:transparent;color:var(--muted);cursor:pointer;padding:4px}.header-links button:hover{color:var(--ink)}.nav-toggle{display:none;border:1px solid var(--line-strong);background:var(--paper);color:var(--ink);border-radius:8px;padding:7px 10px}
.tabs{display:flex;align-items:center;gap:25px;min-height:48px;padding:0 22px;overflow-x:auto;white-space:nowrap}.tab-link{position:relative;color:var(--muted);font-weight:650;font-size:14px;padding:14px 0 15px}.tab-link:hover{color:var(--ink)}.tab-link.active{color:var(--ink)}.tab-link.active:after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:2px;background:var(--brand);border-radius:2px}
.doc-shell{display:grid;grid-template-columns:220px minmax(0,1fr);gap:46px;padding:40px 22px 90px}.sidebar{position:sticky;top:143px;align-self:start;max-height:calc(100vh - 166px);overflow:auto;padding-right:6px}.nav-section{margin:0 0 34px}.nav-section h2{font:750 13px/1.2 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);letter-spacing:0;margin:0 0 14px}.nav-link{display:block;color:var(--muted);border-radius:8px;padding:6px 12px;margin:2px 0;font-size:14px;line-height:1.55}.nav-link:hover{color:var(--ink);background:color-mix(in srgb,var(--paper) 68%,transparent)}.nav-link.active{background:var(--soft);color:var(--brand);font-weight:750}.nav-nested{padding-left:10px;border-left:1px solid var(--line);margin:9px 0 0 6px}.nav-nested h2{font-size:12px;color:var(--muted);margin:0 0 5px;text-transform:none}
.main{min-width:0;display:grid;grid-template-columns:minmax(0,680px) 210px;gap:60px;align-items:start}.article{min-width:0}.article-header{margin:0 0 38px}.article-kicker{color:var(--brand);font-weight:800;font-size:13px;margin:0 0 8px}.article h1{font:760 30px/1.12 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0;color:var(--ink);margin:0}.doc{font-size:15px}.doc>h1:first-child{display:none}.doc h2{font:760 25px/1.22 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);margin:3.0em 0 .65em}.doc h3{font:720 18px/1.28 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);margin:1.8em 0 .45em}.doc h4{font:700 15px/1.35 ui-sans-serif,system-ui,sans-serif;color:var(--ink);margin:1.4em 0 .35em}.doc p,.doc ul,.doc ol,.doc blockquote,.doc table{margin-top:0;margin-bottom:1.12em}.doc ul,.doc ol{padding-left:1.35rem}.doc li{margin:.24em 0}.doc strong{color:var(--ink);font-weight:800}.doc code{background:var(--code);border:1px solid var(--line-strong);border-radius:5px;padding:.08em .36em;font-size:.86em;color:var(--code-text)}.doc pre{position:relative;overflow:auto;background:var(--code);color:var(--code-text);border-radius:10px;padding:16px 18px;border:1px solid var(--line-strong);box-shadow:var(--shadow)}.doc pre code{background:transparent;border:0;color:inherit;padding:0}.doc blockquote{border-left:3px solid var(--line-strong);padding-left:24px;color:var(--text);font-style:italic}.doc table{width:100%;border-collapse:collapse;font-size:14px}.doc th,.doc td{border-bottom:1px solid var(--line);padding:9px;text-align:left;vertical-align:top}.doc th{color:var(--ink);background:var(--paper)}.doc p[align="center"]{text-align:center}.doc p[align="center"] img{margin:0 auto}.anchor{color:var(--muted);padding-right:.35em;text-decoration:none;opacity:.5}.anchor:hover{opacity:1;text-decoration:none}
.toc{position:sticky;top:143px;align-self:start;max-height:calc(100vh - 166px);overflow:auto;color:var(--muted);font-size:14px}.toc h2{display:flex;align-items:center;gap:7px;font:700 13px/1.2 ui-sans-serif,system-ui,sans-serif;color:var(--text);margin:0 0 14px}.toc h2:before{content:"≡";font-size:14px;color:var(--text)}.toc a{display:block;color:var(--muted);line-height:1.4;padding:7px 0}.toc a:hover{color:var(--ink)}.toc a:first-of-type,.toc a.active{color:var(--brand);font-weight:750}.toc-l3{padding-left:12px!important}
.oc-card-grid,.oc-card-group{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:28px 0 28px}.oc-card{display:block;min-height:142px;border:1px solid var(--line-strong);background:transparent;border-radius:12px;padding:22px 24px;color:var(--text)}.oc-card:hover{border-color:var(--brand);color:var(--text)}.oc-card:first-child{border-color:var(--brand)}.oc-card strong{display:block;color:var(--ink);font:750 16px/1.3 ui-sans-serif,system-ui,sans-serif;margin:18px 0 8px}.oc-card p{margin:0;color:var(--muted);line-height:1.55}.oc-card-icon{display:block;width:24px;height:24px;color:var(--brand);stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.oc-steps{counter-reset:step;list-style:none;padding-left:0!important}.oc-step{counter-increment:step;border-left:2px solid var(--line);padding:0 0 12px 22px;position:relative}.oc-step:before{content:counter(step);position:absolute;left:-13px;top:0;width:24px;height:24px;border-radius:50%;background:var(--brand);color:#111;display:grid;place-items:center;font-size:12px;font-weight:800}.oc-step h3{margin-top:0}.oc-callout{border:1px solid var(--line-strong);border-left:4px solid var(--brand);background:var(--paper);border-radius:10px;padding:13px 15px;margin:18px 0}.oc-callout-warning{border-left-color:#d97706}.oc-callout-tip,.oc-callout-check{border-left-color:#48b49a}.oc-tabs{display:grid;gap:10px;margin:16px 0}.oc-tab,.oc-param,.oc-frame,.oc-code-group{border:1px solid var(--line-strong);background:var(--paper);border-radius:10px;padding:13px 15px;margin:12px 0}.oc-tab h3{margin-top:0}.oc-accordion{border:1px solid var(--line-strong);background:var(--paper);border-radius:10px;margin:10px 0;padding:0 13px}.oc-accordion summary{cursor:pointer;color:var(--ink);font-weight:750;padding:12px 0}.oc-param header{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:8px}.oc-param-type,.oc-param-required{border:1px solid var(--line-strong);border-radius:999px;padding:1px 7px;font-size:12px;color:var(--muted)}.oc-param-required{color:var(--brand)}
.page-nav{display:grid;grid-template-columns:1fr 1fr;gap:14px;border-top:1px solid var(--line);margin-top:44px;padding-top:18px}.page-nav a{border:1px solid var(--line-strong);background:var(--paper);border-radius:10px;padding:13px;color:var(--text)}.page-nav a:hover{border-color:var(--brand)}.page-nav small{display:block;color:var(--muted);font-size:11px;text-transform:uppercase}.next{text-align:right}
.search-modal{position:fixed;inset:0;background:rgba(0,0,0,.62);display:none;z-index:50;padding:8vh 18px}.search-modal.open{display:block}.search-panel{max-width:760px;margin:0 auto;background:var(--paper);border:1px solid var(--line-strong);border-radius:14px;box-shadow:var(--shadow);overflow:hidden}.search-head{display:flex;gap:10px;padding:12px;border-bottom:1px solid var(--line)}.search-head input{flex:1;border:1px solid var(--line-strong);border-radius:10px;padding:10px;background:var(--bg);color:var(--text)}.search-head button{border:1px solid var(--line-strong);background:var(--paper-2);color:var(--text);border-radius:9px;padding:0 12px}.search-results{max-height:62vh;overflow:auto;padding:8px 12px 14px}.search-result{display:block;border-bottom:1px solid var(--line);padding:12px;color:var(--text)}.search-result strong{display:block;color:var(--ink)}.search-result p{margin:.35em 0 0;color:var(--muted);font-size:13px}
@media(max-width:1120px){.header-row{grid-template-columns:auto 1fr auto}.header-links a{display:none}.doc-shell{grid-template-columns:210px minmax(0,1fr);gap:34px}.main{grid-template-columns:minmax(0,1fr)}.toc{display:none}}@media(max-width:820px){html{scroll-padding-top:78px}.site-header{position:sticky}.header-row{height:auto;min-height:62px;grid-template-columns:1fr auto;padding:10px 16px;gap:12px}.header-left{order:1}.search-button{order:3;grid-column:1/-1;width:100%}.header-links{order:2}.nav-toggle{display:inline-flex}.tabs{display:none}.doc-shell{display:block;padding:24px 18px 70px}.sidebar{position:fixed;inset:0 18% 0 0;z-index:45;transform:translateX(-100%);transition:transform .2s ease;background:var(--bg);border-right:1px solid var(--line);padding:22px 18px;max-height:none}.sidebar.open{transform:translateX(0)}.article h1{font-size:30px}.oc-card-grid,.oc-card-group{grid-template-columns:1fr}.next{text-align:left}.page-nav{grid-template-columns:1fr}}
`;
}

export function siteJs() {
  return `
const root=document.documentElement;const saved=localStorage.getItem("theme");root.dataset.theme=saved||"dark";document.querySelector("[data-theme-toggle]")?.addEventListener("click",()=>{const next=root.dataset.theme==="dark"?"light":"dark";root.dataset.theme=next;localStorage.setItem("theme",next)});
const sidebar=document.querySelector(".sidebar");document.querySelector("[data-nav-toggle]")?.addEventListener("click",()=>sidebar?.classList.toggle("open"));document.querySelectorAll(".sidebar a").forEach(a=>a.addEventListener("click",()=>sidebar?.classList.remove("open")));
document.querySelector("[data-locale]")?.addEventListener("change",e=>{const url=e.target.selectedOptions[0]?.dataset.url;if(url)location.href=url});
const modal=document.querySelector(".search-modal");const input=document.querySelector("[data-search-input]");const results=document.querySelector("[data-search-results]");let pagefindReady;
function withBase(url){const base=window.OPENCLAW_DOCS_BASE||"";return url.startsWith("/")?base+url:url}
function openSearch(){modal?.classList.add("open");setTimeout(()=>input?.focus(),0);pagefindReady ||= import(withBase("/pagefind/pagefind.js")).then(m=>m.init?.().then?.(()=>m)??m)}
document.querySelectorAll("[data-search-open]").forEach(b=>b.addEventListener("click",openSearch));document.querySelector("[data-search-close]")?.addEventListener("click",()=>modal?.classList.remove("open"));modal?.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch()}if(e.key==="Escape")modal?.classList.remove("open")});
let seq=0;input?.addEventListener("input",async e=>{const q=e.target.value.trim();const id=++seq;if(!q){results.innerHTML="";return}results.innerHTML="<p>Searching...</p>";const pf=await pagefindReady;if(id!==seq)return;const search=await pf.search(q);const items=await Promise.all(search.results.slice(0,12).map(r=>r.data()));if(id!==seq)return;results.innerHTML=items.length?items.map(item=>'<a class="search-result" href="'+withBase(item.url)+'"><strong>'+item.meta.title+'</strong><p>'+item.excerpt+'</p></a>').join(""):"<p>No results.</p>"});
`;
}
