export const chromeStrings = {
  en: {
    communityDismissLabel: "Dismiss and don't show again",
    communityTitle: "Pull up a chair.",
    communityBody: "There’s a place for you in the AI future. Join the Community on Reddit, Discord, and X.",
    communityJoin: "Join",
    communityFollow: "Follow",
    communityJoinLabel: "Join the OpenClaw community on {platform}",
    communityFollowLabel: "Follow OpenClaw on {platform}",
    onThisPage: "On this page",
  },
  "zh-CN": {
    communityDismissLabel: "关闭且不再显示",
    communityTitle: "来坐坐吧。",
    communityBody: "AI 的未来有你的一席之地。欢迎加入 Reddit、Discord 和 X 上的社区。",
    communityJoin: "加入",
    communityFollow: "关注",
    communityJoinLabel: "加入 {platform} 上的 OpenClaw 社区",
    communityFollowLabel: "在 {platform} 上关注 OpenClaw",
    onThisPage: "本页内容",
  },
  "zh-TW": {
    communityDismissLabel: "關閉且不再顯示",
    communityTitle: "來坐坐吧。",
    communityBody: "AI 的未來有你的一席之地。歡迎加入 Reddit、Discord 和 X 上的社群。",
    communityJoin: "加入",
    communityFollow: "追蹤",
    communityJoinLabel: "加入 {platform} 上的 OpenClaw 社群",
    communityFollowLabel: "在 {platform} 上追蹤 OpenClaw",
    onThisPage: "本頁內容",
  },
  "ja-JP": {
    communityDismissLabel: "閉じて今後は表示しない",
    communityTitle: "席をどうぞ。",
    communityBody: "AI の未来には、あなたの居場所があります。Reddit、Discord、X のコミュニティに参加しませんか。",
    communityJoin: "参加",
    communityFollow: "フォロー",
    communityJoinLabel: "{platform} の OpenClaw コミュニティに参加",
    communityFollowLabel: "{platform} で OpenClaw をフォロー",
    onThisPage: "このページの内容",
  },
  es: {
    communityDismissLabel: "Cerrar y no volver a mostrar",
    communityTitle: "Toma asiento.",
    communityBody: "Hay un lugar para ti en el futuro de la IA. Únete a la comunidad en Reddit, Discord y X.",
    communityJoin: "Únete",
    communityFollow: "Sigue",
    communityJoinLabel: "Únete a la comunidad de OpenClaw en {platform}",
    communityFollowLabel: "Sigue a OpenClaw en {platform}",
    onThisPage: "En esta página",
  },
  "pt-BR": {
    communityDismissLabel: "Fechar e não mostrar novamente",
    communityTitle: "Puxe uma cadeira.",
    communityBody: "Há um lugar para você no futuro da IA. Junte-se à comunidade no Reddit, Discord e X.",
    communityJoin: "Entrar",
    communityFollow: "Seguir",
    communityJoinLabel: "Entrar na comunidade OpenClaw no {platform}",
    communityFollowLabel: "Seguir OpenClaw no {platform}",
    onThisPage: "Nesta página",
  },
  ko: {
    communityDismissLabel: "닫고 다시 표시하지 않기",
    communityTitle: "여기 앉으세요.",
    communityBody: "AI의 미래에는 여러분의 자리가 있습니다. Reddit, Discord, X에서 커뮤니티에 함께하세요.",
    communityJoin: "참여",
    communityFollow: "팔로우",
    communityJoinLabel: "{platform}의 OpenClaw 커뮤니티에 참여",
    communityFollowLabel: "{platform}에서 OpenClaw 팔로우",
    onThisPage: "이 페이지에서",
  },
  de: {
    communityDismissLabel: "Schließen und nicht mehr anzeigen",
    communityTitle: "Nimm Platz.",
    communityBody: "In der Zukunft der KI ist Platz für dich. Werde Teil der Community auf Reddit, Discord und X.",
    communityJoin: "Beitreten",
    communityFollow: "Folgen",
    communityJoinLabel: "Der OpenClaw-Community auf {platform} beitreten",
    communityFollowLabel: "OpenClaw auf {platform} folgen",
    onThisPage: "Auf dieser Seite",
  },
  fr: {
    communityDismissLabel: "Fermer et ne plus afficher",
    communityTitle: "Prenez place.",
    communityBody: "Vous avez votre place dans l’avenir de l’IA. Rejoignez la communauté sur Reddit, Discord et X.",
    communityJoin: "Rejoindre",
    communityFollow: "Suivre",
    communityJoinLabel: "Rejoindre la communauté OpenClaw sur {platform}",
    communityFollowLabel: "Suivre OpenClaw sur {platform}",
    onThisPage: "Sur cette page",
  },
  hi: {
    communityDismissLabel: "बंद करें और दोबारा न दिखाएं",
    communityTitle: "आइए, बैठिए।",
    communityBody: "AI के भविष्य में आपके लिए भी जगह है। Reddit, Discord और X पर कम्युनिटी से जुड़ें।",
    communityJoin: "जुड़ें",
    communityFollow: "फ़ॉलो करें",
    communityJoinLabel: "{platform} पर OpenClaw कम्युनिटी से जुड़ें",
    communityFollowLabel: "{platform} पर OpenClaw को फ़ॉलो करें",
    onThisPage: "इस पेज पर",
  },
  ar: {
    communityDismissLabel: "إغلاق وعدم الإظهار مرة أخرى",
    communityTitle: "تفضّل بالجلوس.",
    communityBody: "لك مكان في مستقبل الذكاء الاصطناعي. انضم إلى المجتمع على Reddit وDiscord وX.",
    communityJoin: "انضم",
    communityFollow: "تابع",
    communityJoinLabel: "انضم إلى مجتمع OpenClaw على {platform}",
    communityFollowLabel: "تابع OpenClaw على {platform}",
    onThisPage: "في هذه الصفحة",
  },
  it: {
    communityDismissLabel: "Chiudi e non mostrare più",
    communityTitle: "Accomodati.",
    communityBody: "C’è un posto per te nel futuro dell’IA. Unisciti alla community su Reddit, Discord e X.",
    communityJoin: "Unisciti",
    communityFollow: "Segui",
    communityJoinLabel: "Unisciti alla community OpenClaw su {platform}",
    communityFollowLabel: "Segui OpenClaw su {platform}",
    onThisPage: "In questa pagina",
  },
  vi: {
    communityDismissLabel: "Đóng và không hiển thị lại",
    communityTitle: "Kéo ghế ngồi cùng nhé.",
    communityBody: "Tương lai AI có chỗ dành cho bạn. Tham gia cộng đồng trên Reddit, Discord và X.",
    communityJoin: "Tham gia",
    communityFollow: "Theo dõi",
    communityJoinLabel: "Tham gia cộng đồng OpenClaw trên {platform}",
    communityFollowLabel: "Theo dõi OpenClaw trên {platform}",
    onThisPage: "Trên trang này",
  },
  nl: {
    communityDismissLabel: "Sluiten en niet meer tonen",
    communityTitle: "Schuif gezellig aan.",
    communityBody: "Er is een plek voor jou in de toekomst van AI. Sluit je aan bij de community op Reddit, Discord en X.",
    communityJoin: "Doe mee",
    communityFollow: "Volgen",
    communityJoinLabel: "Doe mee met de OpenClaw-community op {platform}",
    communityFollowLabel: "OpenClaw volgen op {platform}",
    onThisPage: "Op deze pagina",
  },
  fa: {
    communityDismissLabel: "بستن و دیگر نشان ندادن",
    communityTitle: "بفرمایید، بنشینید.",
    communityBody: "در آیندهٔ هوش مصنوعی جایی برای شما هست. به جامعهٔ ما در Reddit، Discord و X بپیوندید.",
    communityJoin: "بپیوندید",
    communityFollow: "دنبال کنید",
    communityJoinLabel: "به جامعهٔ OpenClaw در {platform} بپیوندید",
    communityFollowLabel: "OpenClaw را در {platform} دنبال کنید",
    onThisPage: "در این صفحه",
  },
  tr: {
    communityDismissLabel: "Kapat ve bir daha gösterme",
    communityTitle: "Bir sandalye çek.",
    communityBody: "Yapay zekânın geleceğinde sana da yer var. Reddit, Discord ve X’te topluluğa katıl.",
    communityJoin: "Katıl",
    communityFollow: "Takip et",
    communityJoinLabel: "{platform} üzerindeki OpenClaw topluluğuna katıl",
    communityFollowLabel: "{platform} üzerinde OpenClaw’u takip et",
    onThisPage: "Bu sayfada",
  },
  uk: {
    communityDismissLabel: "Закрити й більше не показувати",
    communityTitle: "Сідайте з нами.",
    communityBody: "У майбутньому ШІ є місце і для вас. Долучайтеся до спільноти в Reddit, Discord та X.",
    communityJoin: "Долучитися",
    communityFollow: "Стежити",
    communityJoinLabel: "Долучитися до спільноти OpenClaw у {platform}",
    communityFollowLabel: "Стежити за OpenClaw у {platform}",
    onThisPage: "На цій сторінці",
  },
  id: {
    communityDismissLabel: "Tutup dan jangan tampilkan lagi",
    communityTitle: "Yuk, duduk bersama.",
    communityBody: "Ada tempat untukmu di masa depan AI. Bergabunglah dengan komunitas di Reddit, Discord, dan X.",
    communityJoin: "Gabung",
    communityFollow: "Ikuti",
    communityJoinLabel: "Gabung komunitas OpenClaw di {platform}",
    communityFollowLabel: "Ikuti OpenClaw di {platform}",
    onThisPage: "Di halaman ini",
  },
  pl: {
    communityDismissLabel: "Zamknij i nie pokazuj ponownie",
    communityTitle: "Przysuń krzesło.",
    communityBody: "W przyszłości AI jest miejsce dla Ciebie. Dołącz do społeczności na Reddicie, Discordzie i X.",
    communityJoin: "Dołącz",
    communityFollow: "Obserwuj",
    communityJoinLabel: "Dołącz do społeczności OpenClaw na {platform}",
    communityFollowLabel: "Obserwuj OpenClaw na {platform}",
    onThisPage: "Na tej stronie",
  },
  ru: {
    communityDismissLabel: "Закрыть и больше не показывать",
    communityTitle: "Присаживайтесь.",
    communityBody: "В будущем ИИ есть место и для вас. Присоединяйтесь к сообществу в Reddit, Discord и X.",
    communityJoin: "Вступить",
    communityFollow: "Подписаться",
    communityJoinLabel: "Вступить в сообщество OpenClaw в {platform}",
    communityFollowLabel: "Подписаться на OpenClaw в {platform}",
    onThisPage: "На этой странице",
  },
  th: {
    communityDismissLabel: "ปิดและไม่ต้องแสดงอีก",
    communityTitle: "มานั่งด้วยกันสิ",
    communityBody: "อนาคตของ AI มีที่สำหรับคุณ มาร่วมชุมชนกับเราบน Reddit, Discord และ X",
    communityJoin: "เข้าร่วม",
    communityFollow: "ติดตาม",
    communityJoinLabel: "เข้าร่วมชุมชน OpenClaw บน {platform}",
    communityFollowLabel: "ติดตาม OpenClaw บน {platform}",
    onThisPage: "ในหน้านี้",
  },
};

export function chromeStringsForLocale(locale) {
  return chromeStrings[locale] ?? chromeStrings.en;
}
