export const chromeStrings = {
  en: {
    communityLabel: "Join the OpenClaw community on Discord",
    communityImageAlt: "A lobster beside the Discord mark on a lit seafloor pedestal",
    communityDismissLabel: "Dismiss and don't show again",
    communityTitle: "Come build with us",
    communityBody: "Ask anything, show what you're making, and find out what everyone else is building. Or just say hi.",
    communityCta: "Join us on Discord",
    onThisPage: "On this page",
  },
  "zh-CN": {
    communityLabel: "加入 OpenClaw 的 Discord 社区",
    communityImageAlt: "一只龙虾站在亮起的海底基座上，旁边是 Discord 标志",
    communityDismissLabel: "关闭且不再显示",
    communityTitle: "来和我们一起构建",
    communityBody: "有问题尽管问，分享你正在做的项目，也看看大家都在构建什么。或者只是来打个招呼。",
    communityCta: "加入我们的 Discord",
    onThisPage: "本页内容",
  },
  "zh-TW": {
    communityLabel: "加入 OpenClaw 的 Discord 社群",
    communityImageAlt: "一隻龍蝦站在發光的海底底座上，旁邊是 Discord 標誌",
    communityDismissLabel: "關閉且不再顯示",
    communityTitle: "和我們一起打造",
    communityBody: "有問題儘管問，分享你正在做的東西，也看看大家都在打造什麼。或只是來打聲招呼。",
    communityCta: "加入我們的 Discord",
    onThisPage: "本頁內容",
  },
  "ja-JP": {
    communityLabel: "Discord の OpenClaw コミュニティに参加",
    communityImageAlt: "海底の光る台座に立つロブスターと Discord のロゴ",
    communityDismissLabel: "閉じて今後は表示しない",
    communityTitle: "一緒につくりましょう",
    communityBody: "何でも質問したり、つくっているものを見せたり、みんなが何をつくっているか見てみましょう。挨拶だけでもどうぞ。",
    communityCta: "Discord に参加",
    onThisPage: "このページの内容",
  },
  es: {
    communityLabel: "Únete a la comunidad de OpenClaw en Discord",
    communityImageAlt: "Una langosta junto al logotipo de Discord sobre un pedestal submarino iluminado",
    communityDismissLabel: "Cerrar y no volver a mostrar",
    communityTitle: "Construye con nosotros",
    communityBody: "Pregunta lo que quieras, comparte lo que estás creando y descubre en qué trabajan los demás. O simplemente saluda.",
    communityCta: "Únete a nuestro Discord",
    onThisPage: "En esta página",
  },
  "pt-BR": {
    communityLabel: "Entre na comunidade OpenClaw no Discord",
    communityImageAlt: "Uma lagosta ao lado do símbolo do Discord em um pedestal iluminado no fundo do mar",
    communityDismissLabel: "Fechar e não mostrar novamente",
    communityTitle: "Venha construir com a gente",
    communityBody: "Pergunte o que quiser, mostre o que está criando e veja o que todo mundo está construindo. Ou só passe para dar um oi.",
    communityCta: "Entre no nosso Discord",
    onThisPage: "Nesta página",
  },
  ko: {
    communityLabel: "Discord의 OpenClaw 커뮤니티에 참여하세요",
    communityImageAlt: "빛나는 해저 받침대 위 Discord 로고 옆에 있는 바닷가재",
    communityDismissLabel: "닫고 다시 표시하지 않기",
    communityTitle: "함께 만들어 보세요",
    communityBody: "무엇이든 물어보고, 만들고 있는 것을 보여주고, 다른 사람들이 무엇을 만드는지 둘러보세요. 가볍게 인사만 해도 좋아요.",
    communityCta: "Discord 참여하기",
    onThisPage: "이 페이지에서",
  },
  de: {
    communityLabel: "Der OpenClaw-Community auf Discord beitreten",
    communityImageAlt: "Ein Hummer neben dem Discord-Logo auf einem beleuchteten Sockel am Meeresgrund",
    communityDismissLabel: "Schließen und nicht mehr anzeigen",
    communityTitle: "Mach mit und bau mit uns",
    communityBody: "Frag alles, zeig, woran du arbeitest, und entdecke, was die anderen bauen. Oder sag einfach Hallo.",
    communityCta: "Unserem Discord beitreten",
    onThisPage: "Auf dieser Seite",
  },
  fr: {
    communityLabel: "Rejoindre la communauté OpenClaw sur Discord",
    communityImageAlt: "Un homard près du logo Discord sur un socle éclairé au fond de la mer",
    communityDismissLabel: "Fermer et ne plus afficher",
    communityTitle: "Construisez avec nous",
    communityBody: "Posez vos questions, montrez ce que vous créez et découvrez les projets des autres. Ou passez simplement dire bonjour.",
    communityCta: "Rejoindre notre Discord",
    onThisPage: "Sur cette page",
  },
  hi: {
    communityLabel: "Discord पर OpenClaw समुदाय से जुड़ें",
    communityImageAlt: "समुद्र तल पर रोशन चबूतरे पर Discord के चिह्न के पास एक लॉब्स्टर",
    communityDismissLabel: "बंद करें और दोबारा न दिखाएं",
    communityTitle: "हमारे साथ बनाएं",
    communityBody: "कुछ भी पूछें, जो बना रहे हैं उसे दिखाएं और जानें कि बाकी लोग क्या बना रहे हैं। या बस नमस्ते कहें।",
    communityCta: "Discord पर हमसे जुड़ें",
    onThisPage: "इस पेज पर",
  },
  ar: {
    communityLabel: "انضم إلى مجتمع OpenClaw على Discord",
    communityImageAlt: "جراد بحر بجوار شعار Discord على منصة مضاءة في قاع البحر",
    communityDismissLabel: "إغلاق وعدم الإظهار مرة أخرى",
    communityTitle: "تعال وابنِ معنا",
    communityBody: "اسأل عن أي شيء، وشارك ما تبنيه، واكتشف ما يبنيه الآخرون. أو تعال فقط لإلقاء التحية.",
    communityCta: "انضم إلينا على Discord",
    onThisPage: "في هذه الصفحة",
  },
  it: {
    communityLabel: "Unisciti alla community di OpenClaw su Discord",
    communityImageAlt: "Un'aragosta accanto al logo di Discord su un piedistallo illuminato sul fondale marino",
    communityDismissLabel: "Chiudi e non mostrare più",
    communityTitle: "Costruisci insieme a noi",
    communityBody: "Chiedi ciò che vuoi, mostra cosa stai creando e scopri cosa stanno costruendo gli altri. Oppure passa solo per un saluto.",
    communityCta: "Unisciti a noi su Discord",
    onThisPage: "In questa pagina",
  },
  vi: {
    communityLabel: "Tham gia cộng đồng OpenClaw trên Discord",
    communityImageAlt: "Một chú tôm hùm cạnh biểu tượng Discord trên bệ phát sáng dưới đáy biển",
    communityDismissLabel: "Đóng và không hiển thị lại",
    communityTitle: "Cùng chúng tôi xây dựng",
    communityBody: "Hãy hỏi bất cứ điều gì, chia sẻ thứ bạn đang làm và xem mọi người đang xây dựng gì. Hoặc chỉ ghé qua chào một tiếng.",
    communityCta: "Tham gia Discord của chúng tôi",
    onThisPage: "Trên trang này",
  },
  nl: {
    communityLabel: "Word lid van de OpenClaw-community op Discord",
    communityImageAlt: "Een kreeft naast het Discord-logo op een verlicht voetstuk op de zeebodem",
    communityDismissLabel: "Sluiten en niet meer tonen",
    communityTitle: "Bouw met ons mee",
    communityBody: "Stel je vragen, laat zien wat je maakt en ontdek waar anderen aan bouwen. Of kom gewoon even hallo zeggen.",
    communityCta: "Kom bij ons op Discord",
    onThisPage: "Op deze pagina",
  },
  fa: {
    communityLabel: "به انجمن OpenClaw در Discord بپیوندید",
    communityImageAlt: "یک خرچنگ دریایی کنار نشان Discord روی سکویی روشن در بستر دریا",
    communityDismissLabel: "بستن و دیگر نشان ندادن",
    communityTitle: "با ما بسازید",
    communityBody: "هر چیزی می‌خواهید بپرسید، چیزی را که می‌سازید نشان دهید و ببینید دیگران چه می‌سازند. یا فقط سلام کنید.",
    communityCta: "در Discord به ما بپیوندید",
    onThisPage: "در این صفحه",
  },
  tr: {
    communityLabel: "Discord'daki OpenClaw topluluğuna katıl",
    communityImageAlt: "Deniz tabanındaki aydınlatılmış bir kaidede Discord logosunun yanında bir ıstakoz",
    communityDismissLabel: "Kapat ve bir daha gösterme",
    communityTitle: "Bizimle birlikte geliştir",
    communityBody: "Aklına geleni sor, üzerinde çalıştığın şeyi göster ve başkalarının neler geliştirdiğini keşfet. Ya da sadece selam ver.",
    communityCta: "Discord'umuza katıl",
    onThisPage: "Bu sayfada",
  },
  uk: {
    communityLabel: "Приєднатися до спільноти OpenClaw у Discord",
    communityImageAlt: "Омар поруч із логотипом Discord на освітленому постаменті на морському дні",
    communityDismissLabel: "Закрити й більше не показувати",
    communityTitle: "Створюймо разом",
    communityBody: "Запитуйте про що завгодно, показуйте, над чим працюєте, і дізнавайтеся, що створюють інші. Або просто привітайтеся.",
    communityCta: "Приєднатися до нашого Discord",
    onThisPage: "На цій сторінці",
  },
  id: {
    communityLabel: "Bergabung dengan komunitas OpenClaw di Discord",
    communityImageAlt: "Seekor lobster di samping logo Discord pada alas bercahaya di dasar laut",
    communityDismissLabel: "Tutup dan jangan tampilkan lagi",
    communityTitle: "Berkarya bersama kami",
    communityBody: "Silakan bertanya, tunjukkan apa yang sedang Anda buat, dan lihat apa yang dibuat orang lain. Atau sekadar menyapa.",
    communityCta: "Bergabung di Discord kami",
    onThisPage: "Di halaman ini",
  },
  pl: {
    communityLabel: "Dołącz do społeczności OpenClaw na Discordzie",
    communityImageAlt: "Homar obok logo Discord na podświetlonym podeście na dnie morza",
    communityDismissLabel: "Zamknij i nie pokazuj ponownie",
    communityTitle: "Twórz razem z nami",
    communityBody: "Pytaj o wszystko, pokaż, co tworzysz, i zobacz, nad czym pracują inni. Albo po prostu się przywitaj.",
    communityCta: "Dołącz do nas na Discordzie",
    onThisPage: "Na tej stronie",
  },
  ru: {
    communityLabel: "Присоединиться к сообществу OpenClaw в Discord",
    communityImageAlt: "Омар рядом с логотипом Discord на освещенном постаменте на морском дне",
    communityDismissLabel: "Закрыть и больше не показывать",
    communityTitle: "Создавайте вместе с нами",
    communityBody: "Задавайте вопросы, показывайте, над чем работаете, и узнавайте, что создают другие. Или просто поздоровайтесь.",
    communityCta: "Присоединиться к нашему Discord",
    onThisPage: "На этой странице",
  },
  th: {
    communityLabel: "เข้าร่วมชุมชน OpenClaw บน Discord",
    communityImageAlt: "กุ้งล็อบสเตอร์ข้างสัญลักษณ์ Discord บนแท่นเรืองแสงใต้ทะเล",
    communityDismissLabel: "ปิดและไม่ต้องแสดงอีก",
    communityTitle: "มาสร้างไปด้วยกัน",
    communityBody: "ถามได้ทุกเรื่อง แชร์สิ่งที่คุณกำลังสร้าง และดูว่าคนอื่นกำลังทำอะไรกัน หรือจะแวะมาทักทายก็ได้",
    communityCta: "เข้าร่วม Discord ของเรา",
    onThisPage: "ในหน้านี้",
  },
};

export function chromeStringsForLocale(locale) {
  return chromeStrings[locale] ?? chromeStrings.en;
}
