// Renderer-owned homepage and navigation copy. Article translations remain source-owned.
// Group order follows English below; tests require every locale to provide every field.
export const homeStrings = {
  en: {
    tagline: ["The AI that really does things.", "Any OS. Any Platform. The lobster way. 🦞"],
    channels: ["Connect a channel", "Use OpenClaw from your chat app.", "See all channels"],
    guides: ["Featured guides", "All guides"],
    guideCards: [["Put tasks on a schedule", "Run recurring jobs and deliver the results to your chat."], ["Give your agent a browser", "Set up a dedicated browser for your agent to use."], ["Run more than one agent", "Separate workspaces, conversations, and responsibilities."]],
    community: ["Community", "Come build with us", "Ask anything, share what you’re making, or just say hi.", "Join us on Discord", "Community forum", "Ask questions and share what you’ve built.", "Read the source, report an issue, or contribute.", "Follow OpenClaw for project news and updates."],
    navigation: ["Get started", "Overview", "Quickstart", "Installation", "Onboarding", "Configuration", "Documentation"],
    controls: ["Search documentation", "Toggle theme", "Toggle navigation menu", "Close menu", "Back to all documentation"],
    release: ["New release", "Read release notes", "See what’s new in this release.", "Latest", "Latest release:"],
  },
  de: {
    tagline: ["Die KI, die wirklich etwas tut.", "Jedes Betriebssystem. Jede Plattform. Auf Hummer-Art. 🦞"],
    channels: ["Einen Kanal verbinden", "Nutze OpenClaw in deiner Chat-App.", "Alle Kanäle ansehen"],
    guides: ["Empfohlene Anleitungen", "Alle Anleitungen"],
    guideCards: [["Aufgaben nach Zeitplan ausführen", "Führe wiederkehrende Aufgaben aus und erhalte die Ergebnisse im Chat."], ["Deinem Agenten einen Browser geben", "Richte einen eigenen Browser für deinen Agenten ein."], ["Mehrere Agenten betreiben", "Trenne Arbeitsbereiche, Gespräche und Zuständigkeiten."]],
    community: ["Community", "Entwickle mit uns", "Stelle Fragen, zeige dein Projekt oder sag einfach Hallo.", "Komm zu uns auf Discord", "Community-Forum", "Stelle Fragen und zeige, was du entwickelt hast.", "Lies den Quellcode, melde Probleme oder trage etwas bei.", "Folge OpenClaw für Neuigkeiten und Updates zum Projekt."],
    navigation: ["Loslegen", "Überblick", "Schnellstart", "Installation", "Ersteinrichtung", "Konfiguration", "Dokumentation"],
    controls: ["Dokumentation durchsuchen", "Darstellung wechseln", "Navigationsmenü umschalten", "Menü schließen", "Zur gesamten Dokumentation"],
    release: ["Neue Version", "Versionshinweise lesen", "Erfahre, was diese Version Neues bietet.", "Aktuell", "Neueste Version:"],
  },
  fr: {
    tagline: ["L’IA qui passe vraiment à l’action.", "Tous les systèmes. Toutes les plateformes. À la manière du homard. 🦞"],
    channels: ["Connecter un canal", "Utilisez OpenClaw depuis votre messagerie.", "Voir tous les canaux"],
    guides: ["Guides à découvrir", "Tous les guides"],
    guideCards: [["Planifier des tâches", "Exécutez des tâches récurrentes et recevez les résultats dans votre messagerie."], ["Donner un navigateur à votre agent", "Configurez un navigateur dédié à votre agent."], ["Utiliser plusieurs agents", "Séparez les espaces de travail, les conversations et les responsabilités."]],
    community: ["Communauté", "Construisons ensemble", "Posez vos questions, partagez vos créations ou venez dire bonjour.", "Rejoignez-nous sur Discord", "Forum communautaire", "Posez des questions et partagez vos réalisations.", "Consultez le code, signalez un problème ou contribuez.", "Suivez OpenClaw pour les actualités et mises à jour du projet."],
    navigation: ["Bien démarrer", "Présentation", "Démarrage rapide", "Installation", "Configuration initiale", "Configuration", "Documentation"],
    controls: ["Rechercher dans la documentation", "Changer de thème", "Afficher ou masquer la navigation", "Fermer le menu", "Revenir à toute la documentation"],
    release: ["Nouvelle version", "Lire les notes de version", "Découvrez les nouveautés de cette version.", "Plus récente", "Dernière version :"],
  },
  es: {
    tagline: ["La IA que de verdad hace cosas.", "Cualquier sistema. Cualquier plataforma. Al estilo langosta. 🦞"],
    channels: ["Conectar un canal", "Usa OpenClaw desde tu aplicación de chat.", "Ver todos los canales"],
    guides: ["Guías destacadas", "Todas las guías"],
    guideCards: [["Programar tareas", "Ejecuta tareas periódicas y recibe los resultados en tu chat."], ["Darle un navegador a tu agente", "Configura un navegador dedicado para tu agente."], ["Usar varios agentes", "Separa espacios de trabajo, conversaciones y responsabilidades."]],
    community: ["Comunidad", "Construye con nosotros", "Pregunta lo que quieras, comparte tus proyectos o ven a saludar.", "Únete a nuestro Discord", "Foro de la comunidad", "Haz preguntas y comparte lo que has creado.", "Consulta el código, informa de un problema o contribuye.", "Sigue a OpenClaw para conocer las noticias y actualizaciones del proyecto."],
    navigation: ["Primeros pasos", "Descripción general", "Inicio rápido", "Instalación", "Configuración inicial", "Configuración", "Documentación"],
    controls: ["Buscar en la documentación", "Cambiar tema", "Mostrar u ocultar la navegación", "Cerrar menú", "Volver a toda la documentación"],
    release: ["Nueva versión", "Leer notas de la versión", "Descubre las novedades de esta versión.", "Última", "Última versión:"],
  },
  "pt-BR": {
    tagline: ["A IA que realmente faz as coisas.", "Qualquer sistema. Qualquer plataforma. Do jeito da lagosta. 🦞"],
    channels: ["Conectar um canal", "Use o OpenClaw no seu aplicativo de chat.", "Ver todos os canais"],
    guides: ["Guias em destaque", "Todos os guias"],
    guideCards: [["Agendar tarefas", "Execute tarefas recorrentes e receba os resultados no chat."], ["Dar um navegador ao seu agente", "Configure um navegador dedicado para o seu agente."], ["Executar vários agentes", "Separe espaços de trabalho, conversas e responsabilidades."]],
    community: ["Comunidade", "Venha construir com a gente", "Tire dúvidas, compartilhe seus projetos ou venha dar um oi.", "Entre no nosso Discord", "Fórum da comunidade", "Faça perguntas e compartilhe o que você criou.", "Leia o código, relate um problema ou contribua.", "Siga o OpenClaw para receber notícias e atualizações do projeto."],
    navigation: ["Primeiros passos", "Visão geral", "Início rápido", "Instalação", "Configuração inicial", "Configuração", "Documentação"],
    controls: ["Pesquisar na documentação", "Alternar tema", "Abrir ou fechar a navegação", "Fechar menu", "Voltar para toda a documentação"],
    release: ["Nova versão", "Ler notas da versão", "Veja as novidades desta versão.", "Mais recente", "Última versão:"],
  },
  ar: {
    tagline: ["الذكاء الاصطناعي الذي ينجز المهام فعلًا.", "أي نظام تشغيل. أي منصة. على طريقة الكركند. 🦞"],
    channels: ["ربط قناة", "استخدم OpenClaw من تطبيق الدردشة لديك.", "عرض جميع القنوات"],
    guides: ["أدلة مميزة", "جميع الأدلة"],
    guideCards: [["جدولة المهام", "شغّل المهام المتكررة وتلقَّ نتائجها في الدردشة."], ["تزويد وكيلك بمتصفح", "جهّز متصفحًا مخصصًا ليستخدمه وكيلك."], ["تشغيل عدة وكلاء", "افصل مساحات العمل والمحادثات والمسؤوليات."]],
    community: ["المجتمع", "شاركنا البناء", "اطرح أسئلتك، أو شارك ما تصنعه، أو ألقِ التحية.", "انضم إلينا على Discord", "منتدى المجتمع", "اطرح الأسئلة وشارك ما أنجزته.", "اقرأ الشيفرة المصدرية، أو أبلغ عن مشكلة، أو ساهم.", "تابع OpenClaw لأخبار المشروع وتحديثاته."],
    navigation: ["ابدأ", "نظرة عامة", "بدء سريع", "التثبيت", "الإعداد الأولي", "التهيئة", "الوثائق"],
    controls: ["البحث في الوثائق", "تبديل المظهر", "فتح قائمة التنقل أو إغلاقها", "إغلاق القائمة", "العودة إلى جميع الوثائق"],
    release: ["إصدار جديد", "قراءة ملاحظات الإصدار", "تعرّف على الجديد في هذا الإصدار.", "الأحدث", "أحدث إصدار:"],
  },
  fa: {
    tagline: ["هوش مصنوعی‌ای که واقعاً کارها را انجام می‌دهد.", "هر سیستم‌عامل. هر پلتفرم. به سبک لابستر. 🦞"],
    channels: ["اتصال یک کانال", "از OpenClaw در برنامهٔ گفت‌وگوی خود استفاده کنید.", "دیدن همهٔ کانال‌ها"],
    guides: ["راهنماهای برگزیده", "همهٔ راهنماها"],
    guideCards: [["زمان‌بندی کارها", "کارهای تکراری را اجرا کنید و نتیجه را در گفت‌وگو دریافت کنید."], ["دادن مرورگر به عامل", "یک مرورگر اختصاصی برای استفادهٔ عامل خود تنظیم کنید."], ["اجرای چند عامل", "فضاهای کاری، گفت‌وگوها و مسئولیت‌ها را جدا کنید."]],
    community: ["جامعه", "با هم بسازیم", "سؤال بپرسید، ساخته‌های خود را به اشتراک بگذارید یا سلام کنید.", "در Discord به ما بپیوندید", "انجمن جامعه", "سؤال بپرسید و ساخته‌های خود را به اشتراک بگذارید.", "کد منبع را بخوانید، مشکلی را گزارش کنید یا مشارکت کنید.", "برای خبرها و به‌روزرسانی‌های پروژه، OpenClaw را دنبال کنید."],
    navigation: ["شروع کار", "نمای کلی", "شروع سریع", "نصب", "راه‌اندازی اولیه", "پیکربندی", "مستندات"],
    controls: ["جست‌وجو در مستندات", "تغییر پوسته", "باز یا بسته کردن منوی پیمایش", "بستن منو", "بازگشت به همهٔ مستندات"],
    release: ["نسخهٔ جدید", "خواندن یادداشت‌های انتشار", "با تازه‌های این نسخه آشنا شوید.", "تازه‌ترین", "تازه‌ترین نسخه:"],
  },
  "zh-CN": {
    tagline: ["真正能做事的 AI。", "任何操作系统，任何平台。龙虾式行动。🦞"],
    channels: ["连接渠道", "在你的聊天应用中使用 OpenClaw。", "查看所有渠道"],
    guides: ["精选指南", "所有指南"],
    guideCards: [["安排定时任务", "运行周期性任务，并将结果发送到聊天中。"], ["为智能体配置浏览器", "配置一个供智能体使用的专用浏览器。"], ["运行多个智能体", "分离工作区、对话和职责。"]],
    community: ["社区", "和我们一起构建", "提出问题，分享你的项目，或来打个招呼。", "加入我们的 Discord", "社区论坛", "提出问题并分享你的作品。", "阅读源码、报告问题或参与贡献。", "关注 OpenClaw，获取项目新闻和更新。"],
    navigation: ["开始使用", "概览", "快速开始", "安装", "初始设置", "配置", "文档"],
    controls: ["搜索文档", "切换主题", "展开或收起导航菜单", "关闭菜单", "返回全部文档"],
    release: ["新版本", "阅读发行说明", "了解此版本的新功能。", "最新", "最新版本："],
  },
  "zh-TW": {
    tagline: ["真正能做事的 AI。", "任何作業系統，任何平台。龍蝦式行動。🦞"],
    channels: ["連接頻道", "在你的聊天應用程式中使用 OpenClaw。", "查看所有頻道"],
    guides: ["精選指南", "所有指南"],
    guideCards: [["安排排程任務", "執行週期性任務，並將結果傳送到聊天中。"], ["為代理設定瀏覽器", "設定一個供代理使用的專用瀏覽器。"], ["執行多個代理", "分開工作區、對話與職責。"]],
    community: ["社群", "和我們一起打造", "提出問題、分享你的專案，或來打聲招呼。", "加入我們的 Discord", "社群論壇", "提出問題並分享你的作品。", "閱讀原始碼、回報問題或參與貢獻。", "追蹤 OpenClaw，取得專案消息與更新。"],
    navigation: ["開始使用", "概覽", "快速開始", "安裝", "初始設定", "設定", "文件"],
    controls: ["搜尋文件", "切換主題", "展開或收合導覽選單", "關閉選單", "返回所有文件"],
    release: ["新版本", "閱讀版本說明", "了解此版本的新功能。", "最新", "最新版本："],
  },
  "ja-JP": {
    tagline: ["本当に仕事をこなす AI。", "どの OS でも、どのプラットフォームでも。ロブスター流で。🦞"],
    channels: ["チャンネルを接続", "チャットアプリから OpenClaw を使いましょう。", "すべてのチャンネルを見る"],
    guides: ["おすすめのガイド", "すべてのガイド"],
    guideCards: [["タスクをスケジュールする", "定期的なタスクを実行し、結果をチャットに届けます。"], ["エージェントにブラウザを用意する", "エージェント専用のブラウザを設定します。"], ["複数のエージェントを実行する", "ワークスペース、会話、担当を分けます。"]],
    community: ["コミュニティ", "一緒につくりましょう", "質問したり、作っているものを共有したり、気軽に挨拶したりしてください。", "Discord に参加", "コミュニティフォーラム", "質問や作ったものを共有しましょう。", "ソースコードを読む、問題を報告する、開発に貢献する。", "OpenClaw をフォローして、プロジェクトのニュースや更新をチェック。"],
    navigation: ["はじめに", "概要", "クイックスタート", "インストール", "初期設定", "設定", "ドキュメント"],
    controls: ["ドキュメントを検索", "テーマを切り替え", "ナビゲーションメニューを開閉", "メニューを閉じる", "ドキュメント一覧に戻る"],
    release: ["新しいリリース", "リリースノートを読む", "このリリースの新機能を確認しましょう。", "最新", "最新リリース:"],
  },
  ko: {
    tagline: ["실제로 일을 해내는 AI.", "어떤 OS든, 어떤 플랫폼이든. 랍스터답게. 🦞"],
    channels: ["채널 연결", "채팅 앱에서 OpenClaw를 사용하세요.", "모든 채널 보기"],
    guides: ["추천 가이드", "모든 가이드"],
    guideCards: [["작업 예약하기", "반복 작업을 실행하고 결과를 채팅으로 받아 보세요."], ["에이전트에 브라우저 제공하기", "에이전트가 사용할 전용 브라우저를 설정하세요."], ["여러 에이전트 실행하기", "작업 공간, 대화, 역할을 분리하세요."]],
    community: ["커뮤니티", "함께 만들어 가요", "무엇이든 질문하고, 만들고 있는 것을 공유하거나, 가볍게 인사하세요.", "Discord 참여하기", "커뮤니티 포럼", "질문하고 만든 것을 공유하세요.", "소스 코드를 읽고, 문제를 제보하거나, 기여하세요.", "OpenClaw를 팔로우하여 프로젝트 소식과 업데이트를 확인하세요."],
    navigation: ["시작하기", "개요", "빠른 시작", "설치", "초기 설정", "설정", "문서"],
    controls: ["문서 검색", "테마 전환", "탐색 메뉴 열기 또는 닫기", "메뉴 닫기", "전체 문서로 돌아가기"],
    release: ["새 릴리스", "릴리스 노트 읽기", "이번 릴리스의 새로운 내용을 확인하세요.", "최신", "최신 릴리스:"],
  },
  hi: {
    tagline: ["वह AI जो सच में काम करता है।", "कोई भी OS। कोई भी प्लेटफ़ॉर्म। लॉब्स्टर के अंदाज़ में। 🦞"],
    channels: ["चैनल जोड़ें", "अपने चैट ऐप से OpenClaw इस्तेमाल करें।", "सभी चैनल देखें"],
    guides: ["चुनिंदा गाइड", "सभी गाइड"],
    guideCards: [["कामों का समय तय करें", "दोहराए जाने वाले काम चलाएँ और नतीजे अपनी चैट में पाएँ।"], ["अपने एजेंट को ब्राउज़र दें", "अपने एजेंट के लिए एक समर्पित ब्राउज़र सेट करें।"], ["एक से ज़्यादा एजेंट चलाएँ", "वर्कस्पेस, बातचीत और ज़िम्मेदारियाँ अलग रखें।"]],
    community: ["समुदाय", "हमारे साथ मिलकर बनाएँ", "सवाल पूछें, अपना काम साझा करें या बस नमस्ते कहें।", "Discord पर हमसे जुड़ें", "समुदाय फ़ोरम", "सवाल पूछें और अपनी बनाई चीज़ें साझा करें।", "सोर्स कोड पढ़ें, समस्या बताएँ या योगदान दें।", "प्रोजेक्ट की खबरों और अपडेट के लिए OpenClaw को फ़ॉलो करें।"],
    navigation: ["शुरू करें", "परिचय", "त्वरित शुरुआत", "इंस्टॉलेशन", "शुरुआती सेटअप", "कॉन्फ़िगरेशन", "दस्तावेज़"],
    controls: ["दस्तावेज़ों में खोजें", "थीम बदलें", "नेविगेशन मेन्यू खोलें या बंद करें", "मेन्यू बंद करें", "सभी दस्तावेज़ों पर लौटें"],
    release: ["नया रिलीज़", "रिलीज़ नोट्स पढ़ें", "इस रिलीज़ में नया क्या है, जानें।", "नवीनतम", "नवीनतम रिलीज़:"],
  },
  it: {
    tagline: ["L’IA che fa davvero le cose.", "Qualsiasi sistema. Qualsiasi piattaforma. Alla maniera dell’aragosta. 🦞"],
    channels: ["Collega un canale", "Usa OpenClaw dalla tua app di chat.", "Vedi tutti i canali"],
    guides: ["Guide in evidenza", "Tutte le guide"],
    guideCards: [["Programma le attività", "Esegui attività ricorrenti e ricevi i risultati in chat."], ["Dai un browser al tuo agente", "Configura un browser dedicato al tuo agente."], ["Esegui più agenti", "Separa spazi di lavoro, conversazioni e responsabilità."]],
    community: ["Community", "Costruiamo insieme", "Fai domande, condividi i tuoi progetti o passa a salutarci.", "Unisciti a noi su Discord", "Forum della community", "Fai domande e condividi ciò che hai creato.", "Leggi il codice, segnala un problema o contribuisci.", "Segui OpenClaw per notizie e aggiornamenti sul progetto."],
    navigation: ["Per iniziare", "Panoramica", "Avvio rapido", "Installazione", "Configurazione iniziale", "Configurazione", "Documentazione"],
    controls: ["Cerca nella documentazione", "Cambia tema", "Apri o chiudi il menu di navigazione", "Chiudi menu", "Torna a tutta la documentazione"],
    release: ["Nuova versione", "Leggi le note di rilascio", "Scopri le novità di questa versione.", "Più recente", "Ultima versione:"],
  },
  vi: {
    tagline: ["AI thực sự làm được việc.", "Mọi hệ điều hành. Mọi nền tảng. Theo cách của tôm hùm. 🦞"],
    channels: ["Kết nối kênh", "Dùng OpenClaw ngay trong ứng dụng trò chuyện.", "Xem tất cả kênh"],
    guides: ["Hướng dẫn nổi bật", "Tất cả hướng dẫn"],
    guideCards: [["Lên lịch công việc", "Chạy công việc định kỳ và nhận kết quả trong cuộc trò chuyện."], ["Trang bị trình duyệt cho agent", "Thiết lập trình duyệt riêng để agent sử dụng."], ["Chạy nhiều agent", "Tách biệt không gian làm việc, cuộc trò chuyện và trách nhiệm."]],
    community: ["Cộng đồng", "Cùng chúng tôi xây dựng", "Đặt câu hỏi, chia sẻ dự án của bạn hoặc ghé qua chào hỏi.", "Tham gia Discord cùng chúng tôi", "Diễn đàn cộng đồng", "Đặt câu hỏi và chia sẻ những gì bạn đã tạo.", "Đọc mã nguồn, báo lỗi hoặc đóng góp.", "Theo dõi OpenClaw để nhận tin tức và cập nhật dự án."],
    navigation: ["Bắt đầu", "Tổng quan", "Bắt đầu nhanh", "Cài đặt", "Thiết lập ban đầu", "Cấu hình", "Tài liệu"],
    controls: ["Tìm kiếm tài liệu", "Đổi giao diện", "Mở hoặc đóng menu điều hướng", "Đóng menu", "Quay lại toàn bộ tài liệu"],
    release: ["Bản phát hành mới", "Đọc ghi chú phát hành", "Khám phá điểm mới trong bản phát hành này.", "Mới nhất", "Bản phát hành mới nhất:"],
  },
  nl: {
    tagline: ["De AI die echt dingen doet.", "Elk besturingssysteem. Elk platform. Op z’n kreefts. 🦞"],
    channels: ["Een kanaal verbinden", "Gebruik OpenClaw vanuit je chatapp.", "Alle kanalen bekijken"],
    guides: ["Uitgelichte handleidingen", "Alle handleidingen"],
    guideCards: [["Taken inplannen", "Voer terugkerende taken uit en ontvang de resultaten in je chat."], ["Je agent een browser geven", "Stel een eigen browser in voor je agent."], ["Meerdere agents gebruiken", "Scheid werkruimtes, gesprekken en verantwoordelijkheden."]],
    community: ["Community", "Bouw met ons mee", "Stel vragen, deel wat je maakt of kom gewoon even hallo zeggen.", "Sluit je aan op Discord", "Communityforum", "Stel vragen en deel wat je hebt gebouwd.", "Lees de broncode, meld een probleem of draag bij.", "Volg OpenClaw voor nieuws en updates over het project."],
    navigation: ["Aan de slag", "Overzicht", "Snelstart", "Installatie", "Eerste configuratie", "Configuratie", "Documentatie"],
    controls: ["Documentatie doorzoeken", "Thema wisselen", "Navigatiemenu openen of sluiten", "Menu sluiten", "Terug naar alle documentatie"],
    release: ["Nieuwe versie", "Versieopmerkingen lezen", "Bekijk wat er nieuw is in deze versie.", "Nieuwste", "Nieuwste versie:"],
  },
  tr: {
    tagline: ["Gerçekten iş yapan yapay zekâ.", "Her işletim sistemi. Her platform. Istakoz usulü. 🦞"],
    channels: ["Bir kanal bağlayın", "OpenClaw’ı sohbet uygulamanızdan kullanın.", "Tüm kanalları görün"],
    guides: ["Öne çıkan kılavuzlar", "Tüm kılavuzlar"],
    guideCards: [["Görevleri zamanlayın", "Yinelenen görevleri çalıştırın ve sonuçları sohbetinize alın."], ["Ajanınıza bir tarayıcı verin", "Ajanınızın kullanması için özel bir tarayıcı kurun."], ["Birden fazla ajan çalıştırın", "Çalışma alanlarını, konuşmaları ve sorumlulukları ayırın."]],
    community: ["Topluluk", "Birlikte geliştirelim", "Sorularınızı sorun, yaptıklarınızı paylaşın veya merhaba deyin.", "Discord’da bize katılın", "Topluluk forumu", "Sorular sorun ve geliştirdiklerinizi paylaşın.", "Kaynak kodunu okuyun, sorun bildirin veya katkıda bulunun.", "Proje haberleri ve güncellemeler için OpenClaw’ı takip edin."],
    navigation: ["Başlayın", "Genel bakış", "Hızlı başlangıç", "Kurulum", "İlk yapılandırma", "Yapılandırma", "Belgeler"],
    controls: ["Belgelerde arayın", "Temayı değiştirin", "Gezinme menüsünü açın veya kapatın", "Menüyü kapatın", "Tüm belgelere dönün"],
    release: ["Yeni sürüm", "Sürüm notlarını okuyun", "Bu sürümdeki yenilikleri keşfedin.", "En yeni", "En yeni sürüm:"],
  },
  uk: {
    tagline: ["ШІ, який справді виконує справи.", "Будь-яка ОС. Будь-яка платформа. По-лобстерськи. 🦞"],
    channels: ["Підключити канал", "Користуйтеся OpenClaw зі свого чату.", "Переглянути всі канали"],
    guides: ["Рекомендовані посібники", "Усі посібники"],
    guideCards: [["Заплануйте завдання", "Виконуйте регулярні завдання й отримуйте результати в чаті."], ["Надайте агенту браузер", "Налаштуйте окремий браузер для свого агента."], ["Запускайте кількох агентів", "Розділяйте робочі простори, розмови та обов’язки."]],
    community: ["Спільнота", "Створюймо разом", "Ставте запитання, діліться своїми проєктами або просто привітайтеся.", "Приєднуйтеся в Discord", "Форум спільноти", "Ставте запитання й діліться своїми напрацюваннями.", "Читайте код, повідомляйте про проблеми або долучайтеся.", "Стежте за OpenClaw, щоб дізнаватися новини й оновлення проєкту."],
    navigation: ["Початок роботи", "Огляд", "Швидкий старт", "Встановлення", "Початкове налаштування", "Конфігурація", "Документація"],
    controls: ["Пошук у документації", "Змінити тему", "Відкрити або закрити меню навігації", "Закрити меню", "Повернутися до всієї документації"],
    release: ["Новий випуск", "Читати примітки до випуску", "Дізнайтеся, що нового в цьому випуску.", "Найновіша", "Найновіший випуск:"],
  },
  id: {
    tagline: ["AI yang benar-benar menyelesaikan pekerjaan.", "OS apa pun. Platform apa pun. Dengan cara lobster. 🦞"],
    channels: ["Hubungkan kanal", "Gunakan OpenClaw dari aplikasi chat Anda.", "Lihat semua kanal"],
    guides: ["Panduan pilihan", "Semua panduan"],
    guideCards: [["Jadwalkan tugas", "Jalankan tugas berulang dan terima hasilnya di chat Anda."], ["Berikan browser untuk agen Anda", "Siapkan browser khusus untuk digunakan agen Anda."], ["Jalankan beberapa agen", "Pisahkan ruang kerja, percakapan, dan tanggung jawab."]],
    community: ["Komunitas", "Mari berkarya bersama", "Ajukan pertanyaan, bagikan proyek Anda, atau sekadar menyapa.", "Bergabunglah di Discord", "Forum komunitas", "Ajukan pertanyaan dan bagikan hasil karya Anda.", "Baca kode sumber, laporkan masalah, atau berkontribusi.", "Ikuti OpenClaw untuk berita dan pembaruan proyek."],
    navigation: ["Mulai", "Ringkasan", "Mulai cepat", "Instalasi", "Penyiapan awal", "Konfigurasi", "Dokumentasi"],
    controls: ["Cari dokumentasi", "Ganti tema", "Buka atau tutup menu navigasi", "Tutup menu", "Kembali ke semua dokumentasi"],
    release: ["Rilis baru", "Baca catatan rilis", "Lihat hal baru dalam rilis ini.", "Terbaru", "Rilis terbaru:"],
  },
  pl: {
    tagline: ["AI, która naprawdę działa.", "Dowolny system. Dowolna platforma. Po homarowemu. 🦞"],
    channels: ["Połącz kanał", "Korzystaj z OpenClaw w swojej aplikacji czatu.", "Zobacz wszystkie kanały"],
    guides: ["Polecane poradniki", "Wszystkie poradniki"],
    guideCards: [["Zaplanuj zadania", "Uruchamiaj cykliczne zadania i odbieraj wyniki na czacie."], ["Udostępnij agentowi przeglądarkę", "Skonfiguruj osobną przeglądarkę dla swojego agenta."], ["Uruchom kilku agentów", "Rozdziel przestrzenie robocze, rozmowy i obowiązki."]],
    community: ["Społeczność", "Twórz razem z nami", "Zadawaj pytania, dziel się projektami lub po prostu się przywitaj.", "Dołącz do nas na Discordzie", "Forum społeczności", "Zadawaj pytania i dziel się tym, co tworzysz.", "Czytaj kod, zgłaszaj problemy lub rozwijaj projekt.", "Obserwuj OpenClaw, aby śledzić wiadomości i aktualizacje projektu."],
    navigation: ["Pierwsze kroki", "Przegląd", "Szybki start", "Instalacja", "Konfiguracja wstępna", "Konfiguracja", "Dokumentacja"],
    controls: ["Przeszukaj dokumentację", "Zmień motyw", "Otwórz lub zamknij menu nawigacji", "Zamknij menu", "Wróć do całej dokumentacji"],
    release: ["Nowa wersja", "Czytaj informacje o wydaniu", "Zobacz, co nowego w tej wersji.", "Najnowsza", "Najnowsze wydanie:"],
  },
  ru: {
    tagline: ["ИИ, который действительно делает дело.", "Любая ОС. Любая платформа. По-лобстерски. 🦞"],
    channels: ["Подключить канал", "Пользуйтесь OpenClaw из своего чата.", "Посмотреть все каналы"],
    guides: ["Рекомендуемые руководства", "Все руководства"],
    guideCards: [["Запланируйте задачи", "Запускайте повторяющиеся задачи и получайте результаты в чате."], ["Дайте агенту браузер", "Настройте отдельный браузер для своего агента."], ["Запускайте нескольких агентов", "Разделяйте рабочие пространства, разговоры и обязанности."]],
    community: ["Сообщество", "Давайте создавать вместе", "Задавайте вопросы, делитесь проектами или просто заходите поздороваться.", "Присоединяйтесь в Discord", "Форум сообщества", "Задавайте вопросы и делитесь своими работами.", "Читайте исходный код, сообщайте о проблемах или вносите вклад.", "Следите за OpenClaw, чтобы узнавать новости и обновления проекта."],
    navigation: ["Начало работы", "Обзор", "Быстрый старт", "Установка", "Первоначальная настройка", "Конфигурация", "Документация"],
    controls: ["Поиск по документации", "Сменить тему", "Открыть или закрыть меню навигации", "Закрыть меню", "Вернуться ко всей документации"],
    release: ["Новая версия", "Читать примечания к выпуску", "Узнайте, что нового в этой версии.", "Последняя", "Последняя версия:"],
  },
  th: {
    tagline: ["AI ที่ลงมือทำงานได้จริง", "ทุกระบบปฏิบัติการ ทุกแพลตฟอร์ม ในแบบฉบับล็อบสเตอร์ 🦞"],
    channels: ["เชื่อมต่อช่องทาง", "ใช้ OpenClaw ผ่านแอปแชตของคุณ", "ดูทุกช่องทาง"],
    guides: ["คู่มือแนะนำ", "คู่มือทั้งหมด"],
    guideCards: [["ตั้งเวลางาน", "เรียกใช้งานที่ทำซ้ำและรับผลลัพธ์ในแชตของคุณ"], ["ให้เอเจนต์ของคุณใช้เบราว์เซอร์", "ตั้งค่าเบราว์เซอร์เฉพาะสำหรับเอเจนต์ของคุณ"], ["เรียกใช้เอเจนต์หลายตัว", "แยกพื้นที่ทำงาน บทสนทนา และหน้าที่รับผิดชอบ"]],
    community: ["ชุมชน", "มาร่วมสร้างไปด้วยกัน", "ถามคำถาม แชร์สิ่งที่คุณกำลังสร้าง หรือแวะมาทักทาย", "เข้าร่วมกับเราบน Discord", "ฟอรัมชุมชน", "ถามคำถามและแชร์ผลงานของคุณ", "อ่านซอร์สโค้ด รายงานปัญหา หรือร่วมพัฒนา", "ติดตาม OpenClaw เพื่อรับข่าวสารและอัปเดตของโครงการ"],
    navigation: ["เริ่มต้นใช้งาน", "ภาพรวม", "เริ่มต้นอย่างรวดเร็ว", "การติดตั้ง", "การตั้งค่าเริ่มต้น", "การกำหนดค่า", "เอกสาร"],
    controls: ["ค้นหาเอกสาร", "เปลี่ยนธีม", "เปิดหรือปิดเมนูนำทาง", "ปิดเมนู", "กลับไปยังเอกสารทั้งหมด"],
    release: ["รุ่นใหม่", "อ่านบันทึกประจำรุ่น", "ดูว่ามีอะไรใหม่ในรุ่นนี้", "ล่าสุด", "รุ่นล่าสุด:"],
  },
};

export function homeStringsForLocale(locale) {
  return homeStrings[locale] ?? homeStrings.en;
}

export function escapeUiText(value) {
  return String(value).replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  })[character]);
}
